services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: sixmansdb
      POSTGRES_PASSWORD: sixmansdb
      POSTGRES_DB: sixmansdle
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
